
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('situations').del()
    .then(function () {
      // Inserts seed entries
      return knex('situations').insert([
        {user_id: 1, category_id:  1, title: 'FIRE FIRE FIRE', situation: 'So, I was home one night and was getting ready to hop in the shower. I had suddenly heard a loud "SMACK".. i walk out and the entire kitchen is on fire, right in front of the scene is my cat, smiling at me.', solution: 'Put out the fire and put my cat up for adoption.'},
        {user_id: 2, category_id:  2, title: 'My Professor Hates Me', situation: 'As I was sitting in Science class, I volunteered to answer the question my Professor was asking. Turns out, my answer was completely incorrect and the entire class was laughing at me, along with my professor.', solution: 'Ran out of class screaming and crying.'},
        {user_id: 3, category_id:  3, title: 'My Co-Worker Keeps Pranking Me', situation: 'Every morning that I arrive to work, my co-worker pranks me. I walk in with my guard up every morning, but this morning was different. I walked into work, and my co worker casually offered me a piece of gum. I attempted to grab a piece that was sticking out in which ended up being a fake pack of gum, and that piece shocked my hand.', solution: 'Screamed and cried, quit my job shortly after the incident.'},
        {user_id: 4, category_id:  4, title: 'My Girlfriend Is Acting Suspicious', situation: 'My girlfriend and I went out on a date last saturday night, and things seemed a bit funky. She was not holding my hand, looking at me, and did not even want to kiss me. I was so curious as to what was going on, so i asked her. She had told me that I smelled really bad due to not showering for the past week.', solution: 'Dumped her on the spot because she is not supportive of my decisions.'},
        {user_id: 5, category_id:  5, title: 'The Guy Sitting In Front Of Me Will Not Stop Talking', situation: 'My wife and I decided to go watch spiderman, and it seems that we dicided to also sit in hte worst place possible. This man in front of us would not stop reciting the words to the movie (seems that he has already watched it) and yelling and screaming. He also smells really bad.', solution: 'I poured all of my popcorn onto his head and told him to be quiet.'},
        {user_id: 6, category_id:  6, title: 'Trying To Get A Playlist Together', situation: 'I have about 300 artists within my iTunes application, but i want to put an entire playlist together containing 50% of the artists that i have so i can work while listening to good music. The problem is, I do not know how i should determine what artists are good for my playlist.', solution: 'I have no solution, currently stuck. SOMEONE HELP'},
        {user_id: 7, category_id:  7, title: 'Softball Tryouts', situation: 'Back when i was trying out for the school softball team last week, something went a bit wrong. The pitcher seemed to have not liked me from the get go, and threw the ball directly at my face when it was my turn to bat.', solution: 'I threw the ball back directly at her face, resulting in the both of us getting suspended from school for a week.'},
        {user_id: 8, category_id:  8, title: 'Buddy', situation: 'I just bought my dog Buddy, he is a Pit Bull / Lab mix. He is a puppy, and still learning how to behave. I walked out of my room yesterday morning and came to find that my entire canvas couch was torn to shreds (which costed me $12,000).', solution: 'Tore all of his toys that i bought him into shreds right in front of him, and saw how he liked it.'},
        {user_id: 9, category_id:  9, title: 'Hiking With My Wife', situation: 'My wife and I recently made a trip over to Yosemite National Park, because we wanted to go out and explore a national park for years. The entire trip was great, until our 3rd day of the 6 day trip. When we had gotten to the peak of our favorite hike, My wife had opened up about a fear that she has always had: heights. I said "babe, why did you decide to tell me about this at the top of the mountain?" She bickered and complained about the event, and she was going to have a helicopter come and resuce her.', solution: 'Walked down the mountain, and at the bottom of the mountain decided to text her and break up with her, and head home.'},
        {user_id: 10, category_id:  10, title: 'My Gym Partner', situation: 'My friend and I decided to get a joined gym membership, because we both needed the motivation. Along with Fitness and Health as it seems, we have not come to a single agreement on what we should do when we get into the gym. Our routines have gone in circles, and i am seeing no progress. I am not exactly sure on how i can handle this.', solution: 'Might have jumped the gun, but i deleted his number and I am now on the lookout for a new gym partner.'},
        {user_id: 11, category_id:  11, title: '200 Wings', situation: 'I had visited a nearby winghouse in a town i had just moved into, and they had an insnane challenge, the 200 wing challenge. IF the customer can finish 200 wings, they are on the house. If the customer couldnt finish the wings, they were going to cost $300. I was really hungry, and down for the challenge.', solution: 'I finished 30, completely vomited all over my plate, and I was $300 poorer than i was when i walked in.'},
        {user_id: 12, category_id:  12, title: 'The $100 Bill', situation: 'As I was waiting for the train in downtown to arrive, i had spotted a $100 bill on the floor. I really wanted to take it but there was a ton of security around. I decided to grab it and run initially because I was paranoid that someone would see.', solution: 'Currently in jail, turns out that one of the security guards had purposefully set that $100 bill there to get someone to do exactly what i did. The cops caught me and arrested me on the spot.'},
        {user_id: 13, category_id:  13, title: 'My Dysfunctional Family', situation: 'My family of 8 (living in one house) can not be the brightest of all families let me tell ya. I am the youngest of my other 7 siblings. My parents seem to favorite all of my other siblings over me and i cant seem to figure out why.', solution: 'I cry about it everynight to my imaginary friends.'},
        {user_id: 14, category_id:  14, title: 'Never Knew My First Cancun Trip Would Be My Last', situation: 'As any other 23 year old guy desires to do, me and 4 of my closest friends went on a trip to Cancun. We might have gone a bit overboard with the drinking one night, and a Group of guys at the bar asked me if i wanted to go out of the bar and explore the city. Me being under the influence, agreed.', solution: 'Right when i walked out of the bar, one of the guys attempted to grab me and throw me into the van parked near us. I woke up on the beach the next morning with my head shaved and left pinky toe missing.'},
        {user_id: 15, category_id:  15, title: 'Double Pay', situation: 'I get paid bi-weekly at my job, and received two paychecks for two weeks, when i was only supposed to receive one.', solution: 'I kept the two paychecks i got, and claimed i didnt get my first. Guess who is going on vacation!!!'}
      ]);
    });
};
